package com.iwaodev.domain.notification;

public enum NotificationTypeEnum {
  ORDER_WAS_PLACED_BY_MEMBER,
  ORDER_STATUS_WAS_UPDATED_BY_ADMIN,
  NEW_PRODUCT_NOW_ON_SALE,
  ORDER_WAS_PLACED_BY_ANONYMOUS,
  ORDER_STATUS_WAS_UPDATED_BY_MEMBER,
  REVIEW_WAS_UPDATED_BY_MEMBER,
  REVIEW_WAS_VERIFIED_BY_ADMIN
}
