version: '3.8'
services:

  spa: 
    image: stsiwo/ec-spa:latest
    container_name: spa 
    depends_on:
      - api
    networks: 
      - frontend
  api:
    image: stsiwo/ec-api:latest
    container_name: api 
    depends_on:
      - db
    networks: 
      - frontend
      - backend 

  db: 
    image: stsiwo/ec-db:latest 
    container_name: db  
    networks: 
      - backend 

networks:
  frontend:
  backend:

