-- MySQL Script generated by MySQL Workbench
-- Thu 25 Mar 2021 12:33:03 PM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ec-schema
-- -----------------------------------------------------
-- stsDev ecommerce schema

-- -----------------------------------------------------
-- Schema ec-schema
--
-- stsDev ecommerce schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ec-schema` DEFAULT CHARACTER SET utf8mb4 ;
USE `ec-schema` ;

-- -----------------------------------------------------
-- Table `ec-schema`.`user_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`user_types` (
  `user_type_id` BIGINT NOT NULL,
  `user_type` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`user_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ec-schema`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`users` (
  `user_id` VARCHAR(36) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `avatar_image_path` VARCHAR(500) NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `deleted_account_date` TIMESTAMP NULL,
  `deleted_account_reason` VARCHAR(1000) NULL,
  `user_type_id` BIGINT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `FK_users__user_types_idx` (`user_type_id` ASC),
  CONSTRAINT `FK_users__user_types`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `ec-schema`.`user_types` (`user_type_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ec-schema`.`phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`phones` (
  `phone_id` BIGINT NOT NULL AUTO_INCREMENT,
  `phone_number` VARCHAR(45) NOT NULL,
  `extension` VARCHAR(10) NULL,
  `country_code` VARCHAR(10) NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`phone_id`),
  INDEX `FK_phones__users_idx` (`user_id` ASC),
  CONSTRAINT `FK_phones__users`
    FOREIGN KEY (`user_id`)
    REFERENCES `ec-schema`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ec-schema`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`addresses` (
  `address_id` BIGINT NOT NULL AUTO_INCREMENT,
  `address_1` VARCHAR(100) NOT NULL,
  `address_2` VARCHAR(100) NULL,
  `city` VARCHAR(100) NOT NULL,
  `province` VARCHAR(100) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `postal_code` VARCHAR(20) NOT NULL,
  `is_billing_address` TINYINT(1) NULL,
  `is_shipping_address` TINYINT(1) NOT NULL DEFAULT 0,
  `user_id` VARCHAR(36) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`address_id`),
  INDEX `FK_addresses_users_idx` (`user_id` ASC),
  CONSTRAINT `FK_addresses_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `ec-schema`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ec-schema`.`product_sizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`product_sizes` (
  `product_size_id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_size_name` VARCHAR(50) NOT NULL,
  `product_size_description` VARCHAR(1000) NULL,
  PRIMARY KEY (`product_size_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ec-schema`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`categories` (
  `category_id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  `category_description` VARCHAR(1000) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ec-schema`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`products` (
  `product_id` VARCHAR(36) NOT NULL,
  `product_name` VARCHAR(500) NOT NULL,
  `product_description` VARCHAR(1000) NOT NULL,
  `product_path` VARCHAR(100) NOT NULL,
  `product_base_unit_price` DECIMAL(13,2) NULL,
  `product_base_discount_price` DECIMAL(13,2) NULL,
  `product_base_discount_start_date` TIMESTAMP NULL,
  `product_base_discount_end_date` TIMESTAMP NULL,
  `average_review_point` DECIMAL(13,2) NOT NULL DEFAULT 0,
  `is_discount` TINYINT(1) NOT NULL DEFAULT 0,
  `is_public` TINYINT(1) NOT NULL DEFAULT 0,
  `category_id` BIGINT NOT NULL,
  `release_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `note` VARCHAR(1000) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`product_id`),
  INDEX `FK_products__categories_idx` (`category_id` ASC),
  CONSTRAINT `FK_products__categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `ec-schema`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ec-schema`.`product_variants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`product_variants` (
  `variant_id` BIGINT NOT NULL AUTO_INCREMENT,
  `variant_size_id` BIGINT NOT NULL,
  `variant_color` VARCHAR(100) NOT NULL,
  `variant_unit_price` DECIMAL(13,2) NULL,
  `variant_discount_price` DECIMAL(13,2) NULL,
  `variant_discount_start_date` TIMESTAMP NULL,
  `variant_discount_end_date` TIMESTAMP NULL,
  `variant_stock` INT(11) NOT NULL DEFAULT 1,
  `is_discount` TINYINT(1) NOT NULL DEFAULT 0,
  `sold_count` INT(11) NOT NULL DEFAULT 0,
  `product_id` VARCHAR(36) NOT NULL,
  `note` VARCHAR(1000) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`variant_id`),
  INDEX `FK_product_variants__product_sizes_idx` (`variant_size_id` ASC),
  INDEX `FK_product_variants__products_idx` (`product_id` ASC),
  CONSTRAINT `FK_product_variants__product_sizes`
    FOREIGN KEY (`variant_size_id`)
    REFERENCES `ec-schema`.`product_sizes` (`product_size_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_product_variants__products`
    FOREIGN KEY (`product_id`)
    REFERENCES `ec-schema`.`products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ec-schema`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`carts` (
  `cart_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(36) NOT NULL,
  `variant_id` BIGINT NOT NULL,
  `is_selected` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`cart_id`),
  INDEX `FK_carts__product_variants` (`variant_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC, `variant_id` ASC),
  INDEX `FK_carts__users` (`user_id` ASC),
  CONSTRAINT `FK_carts__users`
    FOREIGN KEY (`user_id`)
    REFERENCES `ec-schema`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_carts_product_variants`
    FOREIGN KEY (`variant_id`)
    REFERENCES `ec-schema`.`product_variants` (`variant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ec-schema`.`wish_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`wish_lists` (
  `wish_list_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(36) NOT NULL,
  `variant_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`wish_list_id`),
  INDEX `FK_wish_lists__product_variants` (`variant_id` ASC),
  INDEX `FK_wish_lists__users` (`user_id` ASC),
  UNIQUE INDEX `wish_lists_unique` (`user_id` ASC, `variant_id` ASC),
  CONSTRAINT `FK_wish_lists__users`
    FOREIGN KEY (`user_id`)
    REFERENCES `ec-schema`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_wish_lists_product_variants`
    FOREIGN KEY (`variant_id`)
    REFERENCES `ec-schema`.`product_variants` (`variant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ec-schema`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`order_status` (
  `order_status_id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_status_code` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`order_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ec-schema`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`orders` (
  `order_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `order_number` VARCHAR(36) NOT NULL,
  `order_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `payment_date` TIMESTAMP NULL,
  `shipped_date` TIMESTAMP NULL,
  `canceled_date` TIMESTAMP NULL,
  `is_shipped` TINYINT(1) NOT NULL DEFAULT 0,
  `is_paid` TINYINT(1) NOT NULL DEFAULT 0,
  `is_canceled` TINYINT(1) NOT NULL DEFAULT 0,
  `product_cost` DECIMAL(13,2) NOT NULL,
  `tax_cost` DECIMAL(13,2) NOT NULL,
  `note` VARCHAR(1000) NULL,
  `order_status_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`order_id`),
  INDEX `FK_orders__order_status_idx` (`order_status_id` ASC),
  CONSTRAINT `FK_orders__order_status`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `ec-schema`.`order_status` (`order_status_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ec-schema`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`reviews` (
  `review_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(36) NOT NULL,
  `product_id` VARCHAR(36) NOT NULL,
  `review_point` DECIMAL(13,2) NULL,
  `review_title` VARCHAR(100) NULL,
  `review_description` VARCHAR(1000) NULL,
  `is_verified` TINYINT(1) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`review_id`),
  INDEX `FK_reviews_users_idx` (`user_id` ASC),
  INDEX `FK_reviews_products_idx` (`product_id` ASC),
  CONSTRAINT `FK_reviews_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `ec-schema`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_reviews_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `ec-schema`.`products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ec-schema`.`product_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`product_images` (
  `product_image_id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_image_path` VARCHAR(100) NOT NULL,
  `product_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`product_image_id`),
  INDEX `fk_product_images_products1_idx` (`product_id` ASC),
  CONSTRAINT `FK_product_images__products`
    FOREIGN KEY (`product_id`)
    REFERENCES `ec-schema`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ec-schema`.`orders_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec-schema`.`orders_has_products` (
  `order_id` VARCHAR(36) NOT NULL,
  `product_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_orders_has_products_products1_idx` (`product_id` ASC),
  INDEX `fk_orders_has_products_orders1_idx` (`order_id` ASC),
  CONSTRAINT `FK_orders_has_products__orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `ec-schema`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_orders_has_products__products`
    FOREIGN KEY (`product_id`)
    REFERENCES `ec-schema`.`products` (`product_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ec-schema`.`user_types`
-- -----------------------------------------------------
START TRANSACTION;
USE `ec-schema`;
INSERT INTO `ec-schema`.`user_types` (`user_type_id`, `user_type`, `created_at`, `updated_at`) VALUES (1, 'ADMIN', DEFAULT, NULL);
INSERT INTO `ec-schema`.`user_types` (`user_type_id`, `user_type`, `created_at`, `updated_at`) VALUES (2, 'MEMBER', DEFAULT, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ec-schema`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `ec-schema`;
INSERT INTO `ec-schema`.`users` (`user_id`, `first_name`, `last_name`, `email`, `password`, `avatar_image_path`, `is_deleted`, `deleted_account_date`, `deleted_account_reason`, `user_type_id`, `created_at`, `updated_at`) VALUES ('63444de6-9abc-49fa-a170-fa88340d026f', 'test_admin_first_name', 'test_admin_last_name', 'test_admin@test.com', '$2a$10$iRnpNpN7XsJq3wjHwRza1eda6CKz.GnMfLAmnozUXepQnm3w7i1yS', NULL, DEFAULT, NULL, NULL, 1, DEFAULT, NULL);
INSERT INTO `ec-schema`.`users` (`user_id`, `first_name`, `last_name`, `email`, `password`, `avatar_image_path`, `is_deleted`, `deleted_account_date`, `deleted_account_reason`, `user_type_id`, `created_at`, `updated_at`) VALUES ('b3d21d32-7785-4fb0-a074-c7ce2ffa98a2', 'test_member_first_name', 'test_member_last_name', 'test_member@test.com', '$2a$10$iRnpNpN7XsJq3wjHwRza1eda6CKz.GnMfLAmnozUXepQnm3w7i1yS', NULL, DEFAULT, NULL, NULL, 2, DEFAULT, NULL);

COMMIT;

